pdf: thesis.tex 
	latexmk thesis.tex

clean:
	rm thesis.aux thesis.bcf thesis.bbl thesis.blg thesis.fdb_latexmk \
	thesis.fls thesis.lof thesis.log thesis.lot thesis.out thesis.run.xml \
	thesis.synctex.gz thesis.toc auto/ _minted-thesis/ -rf
